In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("C:\\Users\\KIRTHIKA K S\\Downloads\\amazon_product.csv")

In [3]:
type(df)

pandas.core.frame.DataFrame

In [4]:
df.head()

,Unnamed: 0,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN

In [5]:
df.columns

Index(['Unnamed: 0', 'asin', 'product_title', 'product_price',
       'product_original_price', 'currency', 'product_star_rating',
       'product_num_ratings', 'product_url', 'product_photo',
       'product_num_offers', 'product_minimum_offer_price', 'is_best_seller',
       'is_amazon_choice', 'is_prime', 'climate_pledge_friendly',
       'sales_volume', 'delivery', 'has_variations', 'product_availability',
       'unit_price', 'unit_count'],
      dtype='object')

In [6]:
df.isna().sum()

Unnamed: 0                      0
asin                            0
product_title                   0
product_price                   0
product_original_price         37
currency                        0
product_star_rating            10
product_num_ratings             0
product_url                     0
product_photo                   0
product_num_offers              0
product_minimum_offer_price     0
is_best_seller                  0
is_amazon_choice                0
is_prime                        0
climate_pledge_friendly         0
sales_volume                    3
delivery                        1
has_variations                  0
product_availability           63
unit_price                     59
unit_count                     59
dtype: int64

In [8]:
df.duplicated().sum()

0

In [9]:
#DELETE REDUNDANT COLUMNS
df.drop(columns = "Unnamed: 0", inplace = True)

In [10]:
df

,asin,product_title,product_price,product_original_price,currency,product_star_rating,product_num_ratings,product_url,product_photo,product_num_offers,...,is_best_seller,is_amazon_choice,is_prime,climate_pledge_friendly,sales_volume,delivery,has_variations,product_availability,unit_price,unit_count
0,B0BQ118F2T,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,https://www.amazon.com/dp/B0BQ118F2T,https://m.media-amazon.com/images/I/61K1Fz5Lxv...,10,...,False,False,True,False,6K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
1,B0CTD47P22,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,https://www.amazon.com/dp/B0CTD47P22,https://m.media-amazon.com/images/I/51QhB2CfqS...,8,...,False,False,True,False,3K+ bought in past month,"FREE delivery Wed, Aug 7 Only 7 left in stock ...",False,Only 7 left in stock - order soon.,NaN,NaN
2,B0CHH6X6H2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,https://www.amazon.com/dp/B0CHH6X6H2,https://m.media-amazon.com/images/I/812woqv69C...,1,...,False,False,True,False,2K+ bought in past month,"FREE delivery Tue, Aug 6",False,NaN,NaN,NaN
3,B0BZ9XNBRB,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,https://www.amazon.com/dp/B0BZ9XNBRB,https://m.media-amazon.com/images/I/61r7cCpQPl...,30,...,False,False,False,False,10K+ bought in past month,FREE delivery Aug 6 - 8,True,NaN,NaN,NaN
4,B0CN1QSH8Q,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,https://www.amazon.com/dp/B0CN1QSH8Q,https://m.media-amazon.com/images/I/61s0ZzwzSC...,2,...,False,False,True,True,3K+ bought in past month,"FREE delivery Tue, Aug 6",True,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,B0D6LWXK1R,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,https://www.amazon.com/dp/B0D6LWXK1R,https://m.media-amazon.com/images/I/815otxMW0i...,1,...,False,False,False,False,50+ bought in past month,FREE delivery on $35 shipped by Amazon.This ti...,False,NaN,NaN,NaN
60,B0CLKQF5HR,Swan Song,$14.99,$30.00,USD,4.4,14471,https://www.amazon.com/dp/B0CLKQF5HR,https://m.media-amazon.com/images/I/71dSn3QCY6...,1,...,True,False,False,False,Print List Price:,Available instantly,False,NaN,NaN,NaN
61,B0BZFHK12K,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,https://www.amazon.com/dp/B0BZFHK12K,https://m.media-amazon.com/images/I/617GUqQEIC...,1,...,False,False,False,False,"Jul 7, 2023",Available instantly on compatible devices,False,NaN,NaN,NaN
62,B09Z7J4L6X,Xbox Wireless Controller â€“ Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,https://www.amazon.com/dp/B09Z7J4L6X,https://m.media-amazon.com/images/I/71i2tEKlZ2...,1,...,True,False,False,False,"Aug 13, 2024",FREE deliveryThis item will be released on Aug...,False,NaN,NaN,NaN
63,B0CT2R7199,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,https://www.amazon.com/dp/B0CT2R7199,https://m.media-amazon.com/images/I/61+biEwB1h...,1,...,True,False,False,True,80K+ bought in past month,FREE delivery,False,NaN,NaN,NaN

In [11]:
df.columns

Index(['asin', 'product_title', 'product_price', 'product_original_price',
       'currency', 'product_star_rating', 'product_num_ratings', 'product_url',
       'product_photo', 'product_num_offers', 'product_minimum_offer_price',
       'is_best_seller', 'is_amazon_choice', 'is_prime',
       'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='object')

In [14]:
df.drop(columns = ['asin', 'product_url','product_photo', 'product_num_offers', 'product_minimum_offer_price', 'is_amazon_choice', 'is_prime',
       'climate_pledge_friendly', 'sales_volume', 'delivery', 'has_variations' ], inplace = True)

In [15]:
df.columns

Index(['product_title', 'product_price', 'product_original_price', 'currency',
       'product_star_rating', 'product_num_ratings', 'is_best_seller',
       'product_availability', 'unit_price', 'unit_count'],
      dtype='object')

In [16]:
#RENAMING THE COLUMNS
df_new_column_names = []

for i in df.columns:
    df_new_column_names.append(i.capitalize())

In [17]:
df_new_column_names

['Product_title',
 'Product_price',
 'Product_original_price',
 'Currency',
 'Product_star_rating',
 'Product_num_ratings',
 'Is_best_seller',
 'Product_availability',
 'Unit_price',
 'Unit_count']

In [18]:
df.columns = df_new_column_names

In [19]:
df

,Product_title,Product_price,Product_original_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller,Product_availability,Unit_price,Unit_count
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,$169.99,USD,4.0,2929,False,NaN,NaN,NaN
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,$158.00,USD,4.2,135,False,Only 7 left in stock - order soon.,NaN,NaN
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,NaN,USD,3.9,205,False,NaN,NaN,NaN
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,$499.00,USD,4.3,2248,False,NaN,NaN,NaN
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,NaN,USD,4.1,423,False,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,NaN,USD,NaN,0,False,NaN,NaN,NaN
60,Swan Song,$14.99,$30.00,USD,4.4,14471,True,NaN,NaN,NaN
61,Bluey: Let&#x27;s Play!,$0.00,NaN,USD,3.5,270,False,NaN,NaN,NaN
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,$69.99,NaN,USD,2.6,12,True,NaN,NaN,NaN
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,$84.99,USD,4.0,48154,True,NaN,NaN,NaN

In [20]:
#DROPPING DUPLICAES
df.duplicated().sum()

0

In [21]:
df.isna()

,Product_title,Product_price,Product_original_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller,Product_availability,Unit_price,Unit_count
0,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,True,True
2,False,False,True,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,True,True,True
4,False,False,True,False,False,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...
59,False,False,True,False,True,False,False,True,True,True
60,False,False,False,False,False,False,False,True,True,True
61,False,False,True,False,False,False,False,True,True,True
62,False,False,True,False,False,False,False,True,True,True
63,False,False,False,False,False,False,False,True,True,True

In [22]:
df.isna().sum()

Product_title              0
Product_price              0
Product_original_price    37
Currency                   0
Product_star_rating       10
Product_num_ratings        0
Is_best_seller             0
Product_availability      63
Unit_price                59
Unit_count                59
dtype: int64

In [24]:
df.shape

(64, 10)

In [25]:
df.columns

Index(['Product_title', 'Product_price', 'Product_original_price', 'Currency',
       'Product_star_rating', 'Product_num_ratings', 'Is_best_seller',
       'Product_availability', 'Unit_price', 'Unit_count'],
      dtype='object')

In [28]:
#dropping the columns with most na values
df = df[['Product_title', 'Product_price','Currency','Product_star_rating', 'Product_num_ratings', 'Is_best_seller']]

In [29]:
df.head(1)

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,False

In [31]:
df.isna().sum()

Product_title           0
Product_price           0
Currency                0
Product_star_rating    10
Product_num_ratings     0
Is_best_seller          0
dtype: int64

In [32]:
df["Is_best_seller"] = df["Is_best_seller"].apply(lambda x : 1 if x == True else 0)

C:\Users\KIRTHIKA K S\AppData\Local\Temp\ipykernel_18552\3892662101.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Is_best_seller"] = df["Is_best_seller"].apply(lambda x : 1 if x == True else 0)

In [33]:
df

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,$99.99,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",$149.74,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,$49.88,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,$335.00,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",$199.99,USD,4.1,423,0
...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,$34.98,USD,NaN,0,0
60,Swan Song,$14.99,USD,4.4,14471,1
61,Bluey: Let&#x27;s Play!,$0.00,USD,3.5,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,$69.99,USD,2.6,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,$59.99,USD,4.0,48154,1

In [35]:
df['Product_price'] = df['Product_price'].str.replace("$","")

C:\Users\KIRTHIKA K S\AppData\Local\Temp\ipykernel_18552\1695615396.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Product_price'] = df['Product_price'].str.replace("$","")
C:\Users\KIRTHIKA K S\AppData\Local\Temp\ipykernel_18552\1695615396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product_price'] = df['Product_price'].str.replace("$","")

In [36]:
df

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,USD,4.1,423,0
...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,34.98,USD,NaN,0,0
60,Swan Song,14.99,USD,4.4,14471,1
61,Bluey: Let&#x27;s Play!,0.00,USD,3.5,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,69.99,USD,2.6,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,USD,4.0,48154,1

In [39]:
df['Product_price'] = df['Product_price'].astype(float)

C:\Users\KIRTHIKA K S\AppData\Local\Temp\ipykernel_18552\540533000.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product_price'] = df['Product_price'].astype(float)

In [40]:
df

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,99.99,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",149.74,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,49.88,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335.00,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",199.99,USD,4.1,423,0
...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,34.98,USD,NaN,0,0
60,Swan Song,14.99,USD,4.4,14471,1
61,Bluey: Let&#x27;s Play!,0.00,USD,3.5,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,69.99,USD,2.6,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,59.99,USD,4.0,48154,1

In [42]:
df['Product_price'] = df['Product_price'].apply(lambda x : round(x))

C:\Users\KIRTHIKA K S\AppData\Local\Temp\ipykernel_18552\3901059430.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Product_price'] = df['Product_price'].apply(lambda x : round(x))

In [43]:
df

,Product_title,Product_price,Currency,Product_star_rating,Product_num_ratings,Is_best_seller
0,Moto G Play 2023 3-Day Battery Unlocked Made f...,100,USD,4.0,2929,0
1,"SAMSUNG Galaxy A15 5G (SM-156M/DSN), 128GB 6GB...",150,USD,4.2,135,0
2,Total by Verizon | Samsung Galaxy A03s | Locke...,50,USD,3.9,205,0
3,Google Pixel 7a - Unlocked Android Cell Phone ...,335,USD,4.3,2248,0
4,"SAMSUNG Galaxy A15 5G A Series Cell Phone, 128...",200,USD,4.1,423,0
...,...,...,...,...,...,...
59,Greatish Hits: I Followed My Dreams and My Dre...,35,USD,NaN,0,0
60,Swan Song,15,USD,4.4,14471,1
61,Bluey: Let&#x27;s Play!,0,USD,3.5,270,0
62,Xbox Wireless Controller â€“ Sky Cipher Special ...,70,USD,2.6,12,1
63,HP DeskJet 2855e Wireless All-in-One Color Ink...,60,USD,4.0,48154,1

In [44]:
df.to_excel("Cleaned_data.xlsx")